import { TemplateConfig, Section, Header, MenuItem, FontSize } from 'jaldee-widgets';

interface PreviewMenuItem extends MenuItem {
  [key: string]: unknown;
}

interface PreviewAnnouncement {
  message: string;
  foregroundColor?: string;
  backgroundColor?: string;
  fontSize?: FontSize;
  [key: string]: unknown;
}

interface PreviewHeader extends Header {
  [key: string]: unknown;
  menu?: PreviewMenuItem[];
  announcements?: PreviewAnnouncement[];
  actionButton?: { [key: string]: unknown };
}

interface PreviewSection extends Section {
  [key: string]: unknown;
}

export interface PreviewTemplateConfig extends TemplateConfig {
  header?: PreviewHeader;
  sections?: PreviewSection[];
  seo?: { title?: string; [key: string]: unknown };
  [key: string]: unknown;
}

export const previewTemplateConfig: PreviewTemplateConfig = {
  "accountID": 129412,
  "template": "mixed-template1",
  "primaryFont": "'Poppins', sans-serif",
  "secondaryFont": "'Poppins', sans-serif",
  "primaryCustomFontUrl": "DynaPuff",
  "secondaryCustomFontUrl": "DynaPuff",
  "foregroundColor": "",
  "backgroundColor": "",
  "theme": "mediExpat",
  "logo": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/logo.webp",
  "aspectRatio": null,
  "seo": {
    "title": "DhyanDarsh Krishna's Universe",
    "description": "",
    "keywords": "",
    "canonicalUrl": ""
  },
  "header": {
    "name": "header1",
    "title": "",
    "description": "",
    "showCart": true,
    "showLogin": true,
    "showSearch": true,
    "showActionButton": true,
    "foregroundColor": "",
    "backgroundColor": "",
    "actionButton": {
      "text": "Contact Us",
      "link": "/contact",
      "icon": "fa-envelope",
      "foregroundColor": "#ff2424",
      "backgroundColor": "#800000"
    },
    "menu": [
      {
        "id": "ztw7uid",
        "title": "Pre-Book",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "pd06hqo",
        "title": "New Arrivals",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "q5ayis0",
        "title": "Categories",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "jn0u6ib",
        "title": "About Us",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "tdvx4bm",
        "title": "Contact Us",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      }
    ],
    "announcements": [
      {
        "id": "mjbxqqf",
        "message": "<p><span class=\"text-small\">Upto 25% Off + UShipping* &nbsp; &nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; Free Delivery to India</span></p>",
        "fontSize": 11,
        "foregroundColor": "#ffffff",
        "backgroundColor": "#c98d8d"
      },
      {
        "id": "kmbli5n",
        "message": "",
        "fontSize": "",
        "foregroundColor": "",
        "backgroundColor": ""
      }
    ]
  },
  "sections": [
    {
      "id": "id-banner",
      "title": "",
      "subTitle": null,
      "cardType": "banner-card1",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "Accent Top Right",
        "label": "Pre-Order",
        "background": "#6366f1",
        "foreground": "#ffffff"
      },
      "layout": "banner",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/Copilot_20260114_133915.webp",
          "image_aspectRatio": "2",
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/Group%201.webp",
          "image_aspectRatio": "2",
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true
    },
    {
      "id": "id-Categories",
      "title": "Categories",
      "subTitle": "Curated collections crafted for comfort, tradition, and family moments.",
      "cardType": "service-card",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 16,
      "contentSubTitleFontSize": 12,
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "#ffffff",
      "contentBackgroundColor": "#7B1F25",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "custom",
      "className": "my-2 grid rectangle-vertial-rounded pad-hover container",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Pure Linen",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%205R1A9901_d4ae5283-2713-4c27-b13b-22475fa1b813.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Handloom Cotton",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20NRJ_7760_c2e09582-000e-459e-b35f-f46da4f00441.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Handloom Linen",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20NRJ_4711_85dc7d82-3b55-4152-b685-e5d769d1b9ce.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Kanjeevarm Sarees",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20NRJ_2268_e9b0be1a-3afa-4921-8e94-a6155fd03cc5.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Tussar Silk",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20Pure%20Silk%20Digitally%20Printed%20Saree%20Weaved%20With%20Golden%20Zari%20Comes%20With%20Tassels%20-%20Almaari%20Fashion.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Fendi Schiffon",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20NRJ_3943_c97d49e3-d68a-4e77-b1cc-668043e17d35.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Durga Pooja",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20IMG_69312.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Satin Georgette",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#7B1F25",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image%2012.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      }
    },
    {
      "id": "id-prebooking",
      "title": "Pre-Booking Collections",
      "subTitle": "There is high demand for all these sarees! Pre-booking is an excellent way to ensure to get your favourites, especially when they’re flying off the shelves.",
      "cardType": "normal-card",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 12,
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "slider",
      "classType": "group",
      "className": "category-list container gallery my-5",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Aarvi Tissue Cotton Saree",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/Background.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": 5163.33,
          "mrp": 8330,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Green Rajsahi Silk Saree",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/image-element%20%E2%86%92%20NRJ_2268_e9b0be1a-3afa-4921-8e94-a6155fd03cc5.jpg%20%281%29.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": 5163.33,
          "mrp": 8330,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Woven Art Silk Saree in Gree... ",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/Background%20%281%29.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Woven Art Silk Jacquard...",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/greensaree.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": 5163.33,
          "mrp": 8330,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Woven Art Silk Jacquard... ",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/bluesaree.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": 5163.33,
          "mrp": 8330,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_md_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      }
    },
    {
      "id": "id-mhvjrm4us",
      "title": "Shop By Reels",
      "subTitle": "Curated collections crafted for comfort, tradition, and family moments.",
      "cardType": "service-card",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 12,
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Green Glow, Brown Grace",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": "0.8",
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/video/Video_20260107_132027_787.mp4",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Yellow with Sky Blue Combo",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/video/Video_20260107_132526_244.mp4",
          "date": null,
          "price": 650,
          "mrp": 850,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Burnt orange meet coffee brown elegance ..",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/video/Video_20260107_133830_863_1%20%281%29.mp4",
          "date": null,
          "price": 1399,
          "mrp": 1500,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Draped in heritage,Woven with...",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/video/Video_20260107_133205_070_1.mp4",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      }
    },
    {
      "id": "id-x0n79y0q3",
      "title": "New Arrivals",
      "subTitle": "Curated New Arrivals crafted for comfort, tradition, and family moments.",
      "cardType": "item-card",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 12,
      "contentSubTitleFontSize": 12,
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Aarvi Tissue Cotton Saree",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/Background.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": 5163.33,
          "mrp": 8330,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "Accent Top Right",
            "label": "Pre-Order",
            "background": "#16a34a",
            "foreground": "#ffffff"
          }
        },
        {
          "title": "Green Rajsahi Silk Saree",
          "subTitle": "",
          "titleFontSize": "12px",
          "subTitleFontSize": "12px",
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/155646/site_assets/newarrival.jpg.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": 5163.33,
          "mrp": 8330,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_md_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      },
      "cols_xl_options": {
        "items": 6,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false
      }
    }
  ],
  "footer": {
    "visible": true,
    "title": "",
    "displayName": "",
    "description": "",
    "copyright": "",
    "items": [],
    "foregroundColor": "",
    "backgroundColor": ""
  },
  "extras": {
    "store": "",
    "selectedCatalogs": [],
    "location": "",
    "department": "",
    "service": "",
    "user": "",
    "leadSDK": false
  }
} as PreviewTemplateConfig;
