import { TemplateConfig, Section, Header, MenuItem, FontSize } from 'jaldee-widgets';

interface PreviewMenuItem extends MenuItem {
  [key: string]: unknown;
}

interface PreviewAnnouncement {
  message: string;
  foregroundColor?: string;
  backgroundColor?: string;
  fontSize?: FontSize;
  [key: string]: unknown;
}

interface PreviewHeader extends Header {
  [key: string]: unknown;
  menu?: PreviewMenuItem[];
  announcements?: PreviewAnnouncement[];
  actionButton?: { [key: string]: unknown };
}

interface PreviewSection extends Section {
  [key: string]: unknown;
}

export interface PreviewTemplateConfig extends TemplateConfig {
  header?: PreviewHeader;
  sections?: PreviewSection[];
  seo?: { title?: string;[key: string]: unknown };
  [key: string]: unknown;
}

export const tokenTemplate = {
  "token": 1,
  "checkinEncId": "c-42t0b21-1",
  "date": "2026-02-20",
  "providerAccount": {
    "id": 106644,
    "businessName": "DhyanDarsh Hospitals",
    "serviceSector": {
      "id": 1,
      "domain": "healthCare",
      "displayName": "Healthcare",
      "multipleSubDomain": false,
      "multipleLocation": false,
      "lms": false,
      "cdl": false,
      "medicalRecord": false,
      "dentalChart": false,
      "mrAllowedEditTimeInHrs": 0
    },
    "serviceSubSector": {
      "id": 4,
      "subDomain": "hospital",
      "displayName": "Hospital / Nursing Home",
      "menu": false,
      "addFamilyMembers": false,
      "serviceBillable": false,
      "multipleLocation": false
    },
    "licensePkgID": 0,
    "uniqueId": 131294,
    "corpId": 0,
    "branchId": 0,
    "userSubdomain": 0,
    "profileId": 0,
    "accEncUid": "42t0b21",
    "minimumCompleteness": false,
    "businessLogo": [
      {
        "owner": 307959,
        "fileName": "ddhospitals-logo-icon.png",
        "fileSize": 0.1019878387451172,
        "caption": "",
        "fileType": "png",
        "order": 0,
        "s3path": "https://jaldeeproduction.s3.ap-south-1.amazonaws.com/131294/provider/BusinessLogo/307959/17563970907380ddhospitals-logo-icon.png?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEMT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRjBEAiAzBLOQACSJp98Vtwp8C9GamJwaR1Z7nXjInvf6teVhTwIgJCG67ycJALomKYdvBdjI0ii4%2FaI7dvZL3MgC1TXGBxIqyAUIjf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgw5MTM2MzUxNjU0NjUiDDzUtG6riqurdE0UtSqcBXm4YjU09r%2BQpVFLubJ%2Bkpm%2F3srQdCiXvy2sOkoj0JuHlbwEAdOa7m4uMMgrQFDPBPSPbZRd7z6eXOe5IWBUNeVJDQLOs1XyOaxdU9dWJC%2FIEw0%2FzB50oBCNho%2BiTI7TdrCVyd%2BSOkH5CzyGqG292V5MdgbLikEzJ64GGiYrDq8CieiiqmKtl%2Fqu%2F%2BUDcY7LwCVg9d4Tymu3eQUdEFcm%2BqIA1AyYsoBUCYzP8wQI%2FgxDbcY40n1NdjELMnXQ2iycJnRpzEdo7jfl7Mq2cWrJxSGu51q0nckgmi0j34tw5IcgjTe7LDyiRN6RQI8NUBVEp21EDrtjacxJ0Ksgf5BclTB%2BadntizhUWQS3%2BpZRfglJu1vVqsPDvHSvsAGVSCjilMYuOQUi3bZKcvW%2BM4mlh2JMZeiWmiCQ19Lc9t%2FMf2y3RE0tcAzaixc3ryHuaaEFjGJAwSEInAEJ8j0f8vUCrReMQmOLI%2BeMPZG9KwCBiH6hzVKzOO3RxdVJWcLkGYQWdIwzmTvDvJ8M0twZpjoSxeAaF8NXwcF77caISYW3ENzOL8hayrAQg%2FZOxE0spGXHzCw0RJXfHLPU6%2BlbpmZKE%2Fib1peDcWw7fhN5l1DGFnvwvIc%2FZfoH%2BNYyCGySqoBr2sJ8bo5b8%2FmRU1NKx3wEwYg2AMrmYMjoJvSShgOyfu6%2Fyi21wR00bUeDlz%2B2u9yEjH4%2BV7Z3lbk%2BTCIWve67gmf%2Bzrcj%2FLCZdlEqjVGLa2DAWHv3hQtLc%2BxRymmuWO57cMwr4LkoVJy3ZJNOs6ZCDV1vT075spN5gJXfSug2QuSwCbOwL%2F0MUMhW4PiPC%2FiKElEWBvUsS0PSG2paKZZM0ZH9a2poEOdAUz7JEaJrVLqB3ImvyPRq0f57TCWnMKCr38wGOrIBIfx%2F%2F0ofaP104gPuYPKpobFDP5YsLqu2our91XC%2FG8daBLpy%2FhX%2B2XtEsgMFfdc89RWcZKCaU6XoXv4%2FTpVaPQn%2BRWvOtHdC%2BYhq6xYntpT%2Fh7bSiRyH8jwLKFn1PTNv11DJQs288GNdb0OHKSsv%2BO8QrEvP5DYBYCC4x3EX%2BECsVsA%2Fhm%2BBuqyn2cx3NolHXOHk984MvH%2B9qkmkZ78vIKCpMTJBnedc7srXYq7OaohHmA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260220T041930Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=ASIA5JOHGIUMXCH7GKMQ%2F20260220%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Signature=dfb533bda8943e8ef93562c672af323d0e9158c12d98f04fb3c9b5c9a795c1e8",
        "action": "add",
        "uid": "",
        "driveId": 474259
      }
    ]
  },
  "consumer": {
    "id": 431552,
    "firstName": "Manikandan",
    "lastName": "E.V",
    "systemGeneratedDoB": false,
    "phoneNo": "9605551784",
    "favourite": false,
    "phone_verified": false,
    "email_verified": true,
    "jaldeeConsumer": 0,
    "countryCode": "+91",
    "jaldeeId": "6",
    "whatsAppNum": {
      "countryCode": "+91",
      "number": "9605551784"
    },
    "telegramNum": {
      "countryCode": "+91",
      "number": "9605551784"
    },
    "totalCheckedInCount": 0,
    "isSignUpCustomer": false,
    "account": 0,
    "consumerPhoto": [],
    "visitCount": 0,
    "migrated": false,
    "allowLogin": false,
    "internationalConsumer": false,
    "inActivatedBySelf": false,
    "creditSystemGenerated": false
  },
  "jaldeeConsumer": {
    "id": 2040,
    "favourite": false,
    "SignedUp": false,
    "prodAccount": false,
    "accountId": 0,
    "consumerPhoto": []
  },
  "service": {
    "id": 18999,
    "name": "OP Consultation",
    "totalAmount": 0.0,
    "department": 1043,
    "deptName": "General",
    "serviceType": "physicalService",
    "multiples": 1,
    "livetrack": false,
    "consumerNoteMandatory": false,
    "consumerNoteTitle": "Notes",
    "preInfoEnabled": false,
    "preInfoTitle": "",
    "preInfoText": "",
    "postInfoEnabled": false,
    "postInfoTitle": "",
    "postInfoText": "",
    "questionnaireIds": [],
    "maxBookingsAllowed": 0,
    "resoucesRequired": 0,
    "internationalCard": false,
    "bankId": 0,
    "serviceDurationEnabled": false,
    "showPrice": false,
    "serviceOptionIds": [],
    "showOnlyAvailableSlots": false,
    "consumerGroupId": [],
    "date": false,
    "dateTime": false,
    "noDateTime": false,
    "channelRestricted": false,
    "automaticInvoiceGeneration": false,
    "individualScheduleId": 0
  },
  "waitlistStatus": "checkedIn",
  "statusUpdatedTime": "2026-02-20 08:27 AM",
  "partySize": 1,
  "consumerNote": "",
  "recalculatedTime": "2026-02-20",
  "queue": {
    "id": 7328,
    "name": "General Timings",
    "location": {
      "id": 104909,
      "place": "Guruvayur",
      "address": "J24M+RJM, 2nd St, Iringaprom, Kerala 680103, India",
      "longitude": "76.03395424223329",
      "lattitude": "10.607054730120876",
      "googleMapUrl": "https://www.google.com/maps/place/10.607054730120876,76.03395424223329/@10.607054730120876,76.03395424223329,15z",
      "searchable": true,
      "notificationsEnabled": false,
      "walkinNotificationsEnabled": false,
      "OnlineNotificationsEnabled": false,
      "smsEnabled": false,
      "whatsAppEnabled": false,
      "locationType": "googleMap"
    },
    "queueStartTime": "00:01 AM",
    "queueEndTime": "11:59 PM",
    "personAhead": 0,
    "provider": {
      "id": 0,
      "whatsAppNum": {
        "countryCode": "",
        "number": ""
      },
      "telegramNum": {
        "countryCode": "",
        "number": ""
      }
    },
    "availabilityQueue": false
  },
  "waitlistedBy": "PROVIDER_CONSUMER",
  "personsAhead": 0,
  "waitlistingFor": [
    {
      "id": 431552,
      "firstName": "Manikandan",
      "lastName": "E.V",
      "phoneNo": "9605551784",
      "email": "manikandan.ev@gmail.com",
      "memberJaldeeId": "6",
      "title": "",
      "whatsAppNum": {
        "countryCode": "+91",
        "number": "9605551784"
      },
      "telegramNum": {
        "countryCode": "+91",
        "number": "9605551784"
      }
    }
  ],
  "ynwUuid": "477374ec-30ea-48cb-aee7-5e40a86c79b6_wl",
  "paymentStatus": "NotPaid",
  "billStatus": "New",
  "calculationMode": "NoCalc",
  "checkInTime": "00:01",
  "coupons": [],
  "billViewStatus": "Notshow",
  "amountPaid": 0.0,
  "amountDue": 0.0,
  "billId": 0,
  "label": {},
  "waitlistPhoneNumber": "9605551784",
  "account": 106644,
  "onlineRequest": false,
  "kioskRequest": false,
  "firstCheckIn": false,
  "active": false,
  "accessScope": 1,
  "waitlistMode": "ONLINE_CHECKIN",
  "consumerStarted": false,
  "callingStatus": false,
  "showToken": true,
  "hasAttachment": false,
  "mrId": 0,
  "prescriptionCreated": false,
  "prescShared": false,
  "consLastVisitedDate": "20-02-2026 12:01 AM",
  "selfAssign": false,
  "isRescheduled": false,
  "countryCode": "+91",
  "useCredit": false,
  "useJcash": false,
  "jCashUsedAmt": 0.0,
  "creditUsedAmt": 0.0,
  "prevAssignedProvider": 0,
  "teamId": 0,
  "questionnaires": [],
  "deptId": 1043,
  "departmentName": "General",
  "location": {
    "id": 104909,
    "place": "Guruvayur",
    "address": "J24M+RJM, 2nd St, Iringaprom, Kerala 680103, India",
    "longitude": "76.03395424223329",
    "lattitude": "10.607054730120876",
    "googleMapUrl": "https://www.google.com/maps/place/10.607054730120876,76.03395424223329/@10.607054730120876,76.03395424223329,15z",
    "searchable": true,
    "notificationsEnabled": false,
    "walkinNotificationsEnabled": false,
    "OnlineNotificationsEnabled": false,
    "smsEnabled": false,
    "whatsAppEnabled": false,
    "locationType": "googleMap"
  },
  "fullAmt": 0.0,
  "prePayment": 0.0,
  "requestInfo": {
    "agent": "BROWSER",
    "ui": "WEB_UI",
    "ipAddress": "111.92.69.27",
    "bookingReqFrom": "WEB_LINK"
  },
  "serviceOptions": [],
  "serviceName": "OP Consultation",
  "qnrmap": {},
  "serviceDuration": 10,
  "serviceType": "physicalService",
  "serviceTaxable": false,
  "locationUrl": "https://www.google.com/maps/place/10.607054730120876,76.03395424223329/@10.607054730120876,76.03395424223329,15z",
  "serviceData": {
    "id": "18999",
    "name": "OP Consultation"
  },
  "createdDate": "2026-02-20",
  "jCouponAppliedAmt": 0.0,
  "couponAppliedAmt": 0.0,
  "timezone": "Asia/Kolkata",
  "localdate": "20-02-2026",
  "ipRegistrationCreated": false,
  "attachments": [],
  "userSpecificService": false,
  "taxPercentage": 0.0,
  "netTaxAmount": 0.0,
  "taxableTotal": 0.0,
  "nonTaxableTotal": 0.0,
  "netRate": 0.0,
  "discounts": [],
  "discountTotal": 0.0,
  "jaldeeCoupons": [],
  "providerCoupons": [],
  "refundedAmount": 0.0,
  "isAssigned": false,
  "invoiceCreated": false,
  "temporaryTotalAmount": 0.0
}

export const previewTemplateConfig: PreviewTemplateConfig = {
  "accountID": 128609,
  "template": "custom-template",
  "primaryFont": "'Figtree', sans-serif",
  "secondaryFont": "'Figtree', sans-serif",
  "primaryCustomFontUrl": "",
  "secondaryCustomFontUrl": "",
  "theme": "theme-gold",
  "logo": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%203.png",
  "aspectRatio": null,
  "seo": {
    "title": "DhyanDarsh Bakers",
    "description": "DhyanDarsh Bakers",
    "keywords": "",
    "canonicalUrl": ""
  },
  "advertisements": [
    {
      "id": "7kp00dq",
      "title": "",
      "enabled": true,
      "mediaType": "image",
      "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/154843/site_assets/shopify.png",
      "video": "",
      "link": "",
      "altText": "",
      "appearance": "popup-center",
      "delayMilliseconds": 3000
    }
  ],
  "header": {
    "name": "fashion-inline",
    "title": "Kanistha",
    "description": "Booking with Order Template",
    "showCart": true,
    "showHelp": false,
    "showLogin": true,
    "showMobileNavigation": true,
    "showSearch": true,
    "showWishlist": true,
    "showActionButton": false,
    "cartConfig": {
      "displayName": "Cart",
      "icon": "fa-shopping-cart",
      "iconImage": "",
      "hideOnSmallView": true
    },
    "helpConfig": {
      "displayName": "Help",
      "icon": "fa-question-circle",
      "iconImage": "",
      "hideOnSmallView": false
    },
    "loginConfig": {
      "displayName": "Account",
      "icon": "fa-user",
      "iconImage": "",
      "hideOnSmallView": false
    },
    "searchConfig": {
      "displayName": "Search",
      "icon": "fa-search",
      "iconImage": "",
      "hideOnSmallView": false
    },
    "wishlistConfig": {
      "displayName": "Wishlist",
      "icon": "fa-heart",
      "iconImage": "",
      "hideOnSmallView": true
    },
    "foregroundColor": "",
    "backgroundColor": "",
    "actionButton": {
      "text": "Contact Us",
      "link": "/contact",
      "icon": "fa-envelope",
      "foregroundColor": "",
      "backgroundColor": ""
    },
    "menu": [
      {
        "id": "zy8xhnj",
        "title": "Pre-Book",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "7dck3ya",
        "title": "New Arrivals",
        "link": "https://www.jaldee.com/kanistha/items",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "2x21qmk",
        "title": "Shop",
        "link": "https://www.jaldee.com/kanistha/items",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "kr6794u",
        "title": "About Us",
        "link": "aboutus",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "pfb9bsp",
        "title": "Contact Us",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      }
    ],
    "loginMenu": [
      {
        "title": "My Account",
        "link": "profile",
        "linkType": "internal",
        "icon": "fa fa-address-card-o",
        "iconImage": ""
      },
      {
        "title": "My Orders",
        "link": "orders",
        "linkType": "internal",
        "icon": "fa-users",
        "iconImage": ""
      },
      {
        "title": "Logout",
        "link": "logout",
        "linkType": "internal",
        "icon": "fa fa-sign-out",
        "iconImage": ""
      },
      {
        "title": "My Bookings",
        "link": "bookings",
        "linkType": "internal",
        "icon": "",
        "iconImage": ""
      },
      {
        "title": "My Payments",
        "link": "payments",
        "linkType": "internal",
        "icon": "",
        "iconImage": ""
      }
    ],
    "mobileNavigation": [
      {
        "title": "Home",
        "link": "home",
        "linkType": "internal",
        "icon": "fa fa-home",
        "iconImage": ""
      },
      {
        "title": "Shop",
        "link": "items",
        "linkType": "internal",
        "icon": "fa fa-th-large",
        "iconImage": ""
      },
      {
        "title": "Wishlist",
        "link": "order/wishlist",
        "linkType": "internal",
        "icon": "fa fa-heart",
        "iconImage": ""
      },
      {
        "title": "Cart",
        "link": "order/cart",
        "linkType": "internal",
        "icon": "fa fa-shopping-bag",
        "iconImage": ""
      }
    ],
    "announcements": [
      {
        "id": "va3ycv3",
        "message": "<p><span style=\"background-color:rgb(241,245,249);color:rgb(76,70,63);\">Kanistha is woven with love, draped with emotion and meantfor you. We are not just any brand</span></p>",
        "fontSize": "",
        "foregroundColor": "",
        "backgroundColor": "",
        "link": ""
      },
      {
        "id": "69ku7he",
        "message": "<p><span style=\"background-color:rgb(241,245,249);color:rgb(76,70,63);\">we are a name embellished in love, a dream wrapped in six yards, and a story of shared passion</span></p>",
        "fontSize": "",
        "foregroundColor": "",
        "backgroundColor": "",
        "link": ""
      },
      {
        "id": "ittf81s",
        "message": "<p><span style=\"background-color:rgb(241,245,249);color:rgb(76,70,63);\">Named after our Kani, Kanistha was born from a passion that runs deeper than fashion</span></p>",
        "fontSize": "",
        "foregroundColor": "",
        "backgroundColor": "",
        "link": ""
      }
    ],
    "announcement_responsiveness": {
      "cols_xs_options": {
        "items": 1,
        "loop": false,
        "margin": 0,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_md_options": {
        "items": 1,
        "loop": false,
        "margin": 0,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_xl_options": {
        "items": 1,
        "loop": false,
        "margin": 0,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      }
    }
  },
  "sections": [
    {
      "id": "id-0wzvworww",
      "title": "",
      "subTitle": null,
      "cardType": "",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "bold",
      "titleFontWeight": "bold",
      "subTitleFontWeight": "bold",
      "preTitleFontStyle": "",
      "titleFontStyle": "italic",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "left",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "banner",
      "classType": "custom",
      "className": "pt-5",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "items",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_3ccoxl3ccoxl3cco.webp",
          "image_aspectRatio": "2",
          "image_width": 500,
          "image_height": 500,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Purple%20And%20Blue%20Neon%20Vibrant%20Night%20Club%20Party%20Instagram%20Post%20%281%29.webp",
          "image_mob_aspectRatio": "0.8",
          "image_mob_width": 400,
          "image_mob_height": 600,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "items",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": null,
          "image_height": null,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": null,
          "image_mob_height": null,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/154843/site_assets/video/15043222_3840_2160_60fps.mp4",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true
    },
    {
      "id": "id-5l6mak0jh",
      "title": "Trending Collections",
      "subTitle": "Check my latest treding collections",
      "cardType": "item-card2",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "bold",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "italic",
      "titleFontStyle": "italic",
      "subTitleFontStyle": "italic",
      "preTitleTextAlign": "",
      "titleTextAlign": "left",
      "subTitleTextAlign": "left",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "bold",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "italic",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "slider",
      "classType": "custom",
      "className": "py-4",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Semi Silk Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "bold",
          "descriptionFontWeight": "",
          "titleFontStyle": "italic",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "items?categoryId=313&page=0",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_q0x8d5q0x8d5q0x8.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_q0x8d5q0x8d5q0x8.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 450,
          "image_mob_height": 700,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Silk Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "bold",
          "descriptionFontWeight": "",
          "titleFontStyle": "italic",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "items?categoryId=313&page=0",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_synshjsynshjsyns.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_synshjsynshjsyns.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 450,
          "image_mob_height": 700,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Ethnic Collection",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "bold",
          "descriptionFontWeight": "",
          "titleFontStyle": "italic",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "items?categoryId=315&page=0",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Orange%20saree.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Orange%20saree.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 450,
          "image_mob_height": 700,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Daily Wear Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "bold",
          "descriptionFontWeight": "",
          "titleFontStyle": "italic",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "items?categoryId=312&page=0",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Blk%20saree.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Blk%20saree.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 450,
          "image_mob_height": 700,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Silk Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "bold",
          "descriptionFontWeight": "",
          "titleFontStyle": "italic",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "items?categoryId=313,314&page=0",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_xitgalxitgalxitg.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_xitgalxitgalxitg.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 450,
          "image_mob_height": 700,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Semi Jute Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "bold",
          "descriptionFontWeight": "",
          "titleFontStyle": "italic",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "items",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_y83lthy83lthy83l.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 410,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Gemini_Generated_Image_y83lthy83lthy83l.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 300,
          "image_mob_height": 410,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "#e31919",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 3,
        "loop": true,
        "margin": 10,
        "autoplay": true,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": true,
        "nav": false,
        "scrollMode": "marquee"
      },
      "cols_md_options": {
        "items": 3,
        "loop": true,
        "margin": 10,
        "autoplay": true,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": true,
        "nav": false,
        "scrollMode": "marquee"
      },
      "cols_xl_options": {
        "items": 5,
        "loop": true,
        "margin": 10,
        "autoplay": true,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": true,
        "nav": false,
        "scrollMode": "marquee"
      }
    },
    {
      "id": "id-y9k7o0u4f",
      "title": "About Us",
      "subTitle": null,
      "cardType": "about-card2",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "",
      "titleFontStyle": "",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 8,
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "aboutus",
      "classType": "custom",
      "className": "text-center",
      "image": null,
      "titleImage": null,
      "imagePosition": "middle",
      "content": [
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": 8,
          "subTitleFontSize": "",
          "description": "<p>Kanistha is woven with love, draped with emotion and meantfor you. We are not just any brand, we are a name embellished in love, a dream wrapped in six yards, and a story of shared passion.<br>Named after our Kani, Kanistha was born from a passion that runs deeper than fashion. The love for sarees and the spirit of entrepreneurship now celebrates tradition, womanhood, and the emotions woven into every drape. &nbsp;Sarees are never any garments for us. They are memories; ofmothers getting ready for festivals, of celebrations, of pride, grace, and quiet strength. With Kanistha, we want to preserve the elegance and feeling in every drape and pass it on to every woman who wears one of our sarees. &nbsp;<br>We promise that each Kanistha saree is chosenwith care, patience and a heart. From the fabric to the weave, from subtle details to rich textures, every piece reflects our belief that a saree should make a woman feel confident, connected, and beautiful—inside and out.</p>",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2071.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 600,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": 8,
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2074.png",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": 8,
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2073.png",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true
    },
    {
      "id": "id-c6rb2s0b8",
      "title": "Shop By Reels",
      "subTitle": null,
      "cardType": "item-video-card",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "",
      "titleFontStyle": "",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Green Silk Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "center",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/whatmore_poster_230ddafc-2841-4b80-89a9-0cfb7464fa10.webp%20%281%29.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_132027_787.mp4",
          "video_mob": "",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Yellow & Sky Blue Saree",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "item/32113efe-7a73-40ed-8a46-f88ed43cffdc_socit?itemEncid=32113efe-7a73-40ed-8a46-f88ed43cffdc_socit",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/whatmore_poster_230ddafc-2841-4b80-89a9-0cfb7464fa10.webp%20%282%29.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_132526_244.mp4",
          "video_mob": "",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Burnt orange meet coffee brown elegance",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Screenshot%202026-03-12%20164035.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_133830_863_1%20%281%29.mp4",
          "video_mob": "",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Draped in heritage,Woven with..",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/Screenshot%202026-03-12%20164110.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_133205_070_1.mp4",
          "video_mob": "",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 1,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      }
    },
    {
      "id": "id-4uhd0ysgs",
      "title": "Shop by Category",
      "subTitle": null,
      "cardType": "normal-card",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "",
      "titleFontStyle": "",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Semi Jute",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "item/4a82648b-f0ce-4d1f-9415-554d566123c2_socit?itemEncid=4a82648b-f0ce-4d1f-9415-554d566123c2_socit",
          "foregroundColor": "#ffffff",
          "backgroundColor": "#690000",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0007%20-%20Kanistha%20Boutique.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0007%20-%20Kanistha%20Boutique.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 300,
          "image_mob_height": 450,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Semi Silk",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "item/b4f0a16a-774d-47fb-853e-99f623840ebb_socit?itemEncid=b4f0a16a-774d-47fb-853e-99f623840ebb_socit",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0020%20-%20Kanistha%20Boutique.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0020%20-%20Kanistha%20Boutique.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 300,
          "image_mob_height": 450,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Kalyani Cotton",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "item/c7261553-66d5-42d0-b2ef-ccf83a9209aa_socit?itemEncid=c7261553-66d5-42d0-b2ef-ccf83a9209aa_socit",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0022%20-%20Kanistha%20Boutique.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0022%20-%20Kanistha%20Boutique.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 300,
          "image_mob_height": 450,
          "video": "",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Daily Wear",
          "subTitle": "",
          "titleFontSize": "",
          "subTitleFontSize": "",
          "description": "",
          "descriptionFontSize": "",
          "titleFontWeight": "",
          "subTitleFontWeight": "",
          "descriptionFontWeight": "",
          "titleFontStyle": "",
          "subTitleFontStyle": "",
          "descriptionFontStyle": "",
          "titleTextAlign": "",
          "subTitleTextAlign": "",
          "descriptionTextAlign": "",
          "useSectionFontSizes": true,
          "link": "item/32113efe-7a73-40ed-8a46-f88ed43cffdc_socit?itemEncid=32113efe-7a73-40ed-8a46-f88ed43cffdc_socit",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0021%20-%20Kanistha%20Boutique.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "https://jaldeeui.s3.ap-south-1.amazonaws.com/131332/site_assets/IMG-20260309-WA0021%20-%20Kanistha%20Boutique.webp",
          "image_mob_aspectRatio": "custom",
          "image_mob_width": 300,
          "image_mob_height": 450,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/154843/site_assets/video/Video_20260107_132526_244%20%281%29.mp4",
          "video_mob": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      }
    },
    {
      "id": "id-z9ymta95g",
      "title": "Customer Stories",
      "subTitle": null,
      "cardType": "testimonial-card",
      "containerType": "container-fluid",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "",
      "titleFontStyle": "",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "slider",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [],
      "contentType": "dynamic",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 1,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_md_options": {
        "items": 1,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_xl_options": {
        "items": 3,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      }
    },
    {
      "id": "id-dzh4rbsef",
      "title": "Categories",
      "subTitle": "Kanistha is woven with love, draped with emotion and meantfor you. We are not just any brand, we are a name embellished in love, a dream wrapped in six yards, and a story of shared passion. Named after our Kani, Kanistha was born from a passion that runs deeper than fashion. The love for sarees and the spirit of entrepreneurship now celebrates tradition, womanhood, and the emotions woven into every drape.  Sarees are never any garments for us. They are memories; ofmothers getting ready for festivals, of celebrations, of pride, grace, and quiet strength. With Kanistha, we want to preserve the elegance and feeling in every drape and pass it on to every woman who wears one of our sarees.   We promise that each Kanistha saree is chosenwith care, patience and a heart. From the fabric to the weave, from subtle details to rich textures, every piece reflects our belief that a saree should make a woman feel confident, connected, and beautiful—inside and out.",
      "cardType": "",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "",
      "titleFontStyle": "",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_md_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_xl_options": {
        "items": 6,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      }
    },
    {
      "id": "id-ikqelrul8",
      "title": "",
      "subTitle": null,
      "cardType": "",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "preTitleFontWeight": "",
      "titleFontWeight": "",
      "subTitleFontWeight": "",
      "preTitleFontStyle": "",
      "titleFontStyle": "",
      "subTitleFontStyle": "",
      "preTitleTextAlign": "",
      "titleTextAlign": "",
      "subTitleTextAlign": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentTitleFontWeight": "",
      "contentSubTitleFontWeight": "",
      "contentDescriptionFontWeight": "",
      "contentTitleFontStyle": "",
      "contentSubTitleFontStyle": "",
      "contentDescriptionFontStyle": "",
      "contentTitleTextAlign": "",
      "contentSubTitleTextAlign": "",
      "contentDescriptionTextAlign": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [],
      "contentType": "dynamic",
      "key": "Veg Items",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 1,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false,
        "scrollMode": "slide"
      }
    }
  ],
  "footer": {
    "visible": true,
    "title": "",
    "displayName": "",
    "description": "",
    "copyright": "Copyright @ 2026 | Powered by Jaldee Soft Pvt Ltd",
    "logo": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/Frame%201.png",
    "logoAspectRatio": null,
    "variant": "fashion-4col",
    "brandName": "",
    "addressLine1": "Vandana House, Palakkal Devi Temple Road",
    "addressLine2": "Ramanattukara, Kozhikode, Kerala 673633",
    "showDivider": true,
    "socialLinks": [
      {
        "platform": "instagram",
        "url": "https://instagram.com",
        "icon": "fa-instagram",
        "iconImage": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png",
        "visible": true
      }
    ],
    "columns": [
      {
        "title": "Quick Links",
        "links": [
          {
            "label": "Home",
            "link": "",
            "visible": true
          },
          {
            "label": "About Us",
            "link": "about",
            "visible": true
          },
          {
            "label": "Contact Us",
            "link": "contact",
            "visible": true
          },
          {
            "label": "Collections",
            "link": "items",
            "visible": true
          }
        ]
      },
      {
        "title": "Policies",
        "links": [
          {
            "label": "Privacy Policy",
            "link": "privacy",
            "visible": true
          },
          {
            "label": "Refund Policy",
            "link": "refund",
            "visible": true
          },
          {
            "label": "Shipping Policy",
            "link": "shipping",
            "visible": true
          }
        ]
      },
      {
        "title": "Best Sellers",
        "links": [
          {
            "label": "Pre-Orders",
            "link": "preorders",
            "visible": true
          },
          {
            "label": "Premium Collections",
            "link": "premium",
            "visible": true
          },
          {
            "label": "New Arrivals",
            "link": "newarrivals",
            "visible": true
          },
          {
            "label": "Sale",
            "link": "sales",
            "visible": true
          }
        ]
      }
    ],
    "items": [
      {
        "title": "",
        "link": "/",
        "displayName": "Home",
        "icon": "",
        "visible": true
      },
      {
        "title": "phone",
        "link": "9605551784",
        "displayName": "Phone",
        "icon": "",
        "visible": true
      },
      {
        "title": "twitter",
        "link": "",
        "displayName": "Twitter",
        "icon": "",
        "visible": false
      },
      {
        "title": "shipping",
        "link": "",
        "displayName": "Shipping Policy",
        "icon": "",
        "visible": false
      },
      {
        "title": "about",
        "link": "",
        "displayName": "About Us",
        "icon": "",
        "visible": true
      },
      {
        "title": "contact",
        "link": "",
        "displayName": "Contact Us",
        "icon": "",
        "visible": true
      },
      {
        "title": "terms",
        "link": "",
        "displayName": "Terms & Conditions",
        "icon": "",
        "visible": true
      },
      {
        "title": "blogs",
        "link": "",
        "displayName": "Blogs",
        "icon": "",
        "visible": true
      }
    ],
    "foregroundColor": "#ffffff",
    "backgroundColor": "#000000"
  },
  "extras": {
    "store": "s-72t5c44-1",
    "selectedCatalogs": [
      "soc-6101458-4",
      "soc-6101458-3",
      "soc-72t5c44-1"
    ],
    "leadSDK": false
  }
} as PreviewTemplateConfig;

