import { TemplateConfig, Section, Header, MenuItem, FontSize } from 'jaldee-widgets';

interface PreviewMenuItem extends MenuItem {
  [key: string]: unknown;
}

interface PreviewAnnouncement {
  message: string;
  foregroundColor?: string;
  backgroundColor?: string;
  fontSize?: FontSize;
  [key: string]: unknown;
}

interface PreviewHeader extends Header {
  [key: string]: unknown;
  menu?: PreviewMenuItem[];
  announcements?: PreviewAnnouncement[];
  actionButton?: { [key: string]: unknown };
}

interface PreviewSection extends Section {
  [key: string]: unknown;
}

export interface PreviewTemplateConfig extends TemplateConfig {
  header?: PreviewHeader;
  sections?: PreviewSection[];
  seo?: { title?: string; [key: string]: unknown };
  [key: string]: unknown;
}

export const previewTemplateConfig: PreviewTemplateConfig = {
  "accountID": 46806,
  "template": "mixed-template1",
  "primaryFont": "'Figtree', sans-serif",
  "secondaryFont": "'Figtree', sans-serif",
  "primaryCustomFontUrl": "",
  "secondaryCustomFontUrl": "",
  "theme": "theme-black1",
  "logo": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%203.png",
  "aspectRatio": null,
  "seo": {
    "title": "",
    "description": "",
    "keywords": "",
    "canonicalUrl": ""
  },
  "header": {
    "name": "fashion",
    "title": "Dhyan Clinic",
    "description": "Booking with Order Template",
    "showCart": true,
    "showLogin": true,
    "showSearch": true,
    "showActionButton": false,
    "foregroundColor": "",
    "backgroundColor": "",
    "actionButton": {
      "text": "Contact Us",
      "link": "/contact",
      "icon": "fa-envelope",
      "foregroundColor": "",
      "backgroundColor": ""
    },
    "menu": [
      {
        "id": "zy8xhnj",
        "title": "Pre-Book",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "7dck3ya",
        "title": "New Arrivals",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "2x21qmk",
        "title": "Categories",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "kr6794u",
        "title": "About Us",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      },
      {
        "id": "pfb9bsp",
        "title": "Contact Us",
        "link": "",
        "linkType": "internal",
        "icon": "",
        "parentId": null,
        "isCustomPage": false,
        "customPageName": "",
        "customPageData": {
          "seo": {
            "title": "",
            "description": "",
            "keywords": "",
            "canonicalUrl": ""
          }
        },
        "submenu": []
      }
    ],
    "announcements": [
      {
        "id": "l6ts6o0",
        "message": "<p>Kanistha Welcomes you</p>",
        "fontSize": 12,
        "foregroundColor": "",
        "backgroundColor": "#B8AB98"
      }
    ]
  },
  "sections": [
    {
      "id": "id-0wzvworww",
      "title": "",
      "subTitle": null,
      "cardType": "",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "banner",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/424d05dce5ff3ec9c943a611a44a1b296be65215.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true
    },
    {
      "id": "id-5l6mak0jh",
      "title": "Shop The Look",
      "subTitle": null,
      "cardType": "item-card2",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "slider",
      "classType": "custom",
      "className": "py-4",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Red Lehenga",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2058.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Green Silk Lehenga",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2059.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Salwar Kameez",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2063.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Maroon Casual Curta Set",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2060.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Brown Banarasi Silk",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2061%20-%20Copy.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Green Silk Lehenga",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/login%2Bcover.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 700,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 1,
        "loop": true,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": true,
        "nav": false
      },
      "cols_md_options": {
        "items": 3,
        "loop": true,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": true,
        "nav": false
      },
      "cols_xl_options": {
        "items": 5,
        "loop": true,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": true,
        "nav": false
      }
    },
    {
      "id": "id-y9k7o0u4f",
      "title": "About Us",
      "subTitle": null,
      "cardType": "about-card2",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 8,
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "aboutus",
      "classType": "custom",
      "className": "text-center",
      "image": null,
      "titleImage": null,
      "imagePosition": "middle",
      "content": [
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": "8px",
          "subTitleFontSize": null,
          "description": "<p>Kanistha is woven with love, draped with emotion and meantfor you. We are not just any brand, we are a name embellished in love, a dream wrapped in six yards, and a story of shared passion.<br>Named after our Kani, Kanistha was born from a passion that runs deeper than fashion. The love for sarees and the spirit of entrepreneurship now celebrates tradition, womanhood, and the emotions woven into every drape. &nbsp;Sarees are never any garments for us. They are memories; ofmothers getting ready for festivals, of celebrations, of pride, grace, and quiet strength. With Kanistha, we want to preserve the elegance and feeling in every drape and pass it on to every woman who wears one of our sarees. &nbsp;<br>We promise that each Kanistha saree is chosenwith care, patience and a heart. From the fabric to the weave, from subtle details to rich textures, every piece reflects our belief that a saree should make a woman feel confident, connected, and beautiful—inside and out.</p>",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2071.webp",
          "image_aspectRatio": "custom",
          "image_width": 450,
          "image_height": 600,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": "8px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2074.png",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "",
          "subTitle": "",
          "titleFontSize": "8px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2073.png",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true
    },
    {
      "id": "id-4uhd0ysgs",
      "title": "Most Wishlisted Styles",
      "subTitle": null,
      "cardType": "item-card2",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Embroidary Saree Styles",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2064.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Silk Sarees",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2065.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Banarasi Silk Sarees",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2066.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Kanchi Silk Sarees",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2067.webp",
          "image_aspectRatio": "custom",
          "image_width": 300,
          "image_height": 450,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      }
    },
    {
      "id": "id-gooh2zqua",
      "title": "",
      "subTitle": null,
      "cardType": "text-card",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": 16,
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "custom",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Privacy Policy",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Refund Policy",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Shipping Policy",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Terms & Conditions",
          "subTitle": "",
          "titleFontSize": "16px",
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      }
    },
    {
      "id": "id-c6rb2s0b8",
      "title": "Shop By Reels",
      "subTitle": null,
      "cardType": "item-video-card",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "grid",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Green Glow, Brown Grace",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/whatmore_poster_230ddafc-2841-4b80-89a9-0cfb7464fa10.webp%20%281%29.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_132027_787.mp4",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Yellow with Sky Blue Combo",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/whatmore_poster_230ddafc-2841-4b80-89a9-0cfb7464fa10.webp%20%282%29.webp",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_132526_244.mp4",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Burnt orange meet coffee brown elegance",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/greensaree.jpg.png",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_133830_863_1%20%281%29.mp4",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Draped in heritage,Woven with..",
          "subTitle": "",
          "titleFontSize": null,
          "subTitleFontSize": null,
          "description": "",
          "descriptionFontSize": null,
          "useSectionFontSizes": true,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/bluesaree.jpg.png",
          "image_aspectRatio": null,
          "image_width": 500,
          "image_height": 500,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/video/Video_20260107_133205_070_1.mp4",
          "date": null,
          "price": 1380,
          "mrp": 2000,
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_md_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_xl_options": {
        "items": 4,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      }
    },
    {
      "id": "id-z9ymta95g",
      "title": "Customer Stories",
      "subTitle": null,
      "cardType": "testimonial-card",
      "containerType": "container",
      "preTitle": null,
      "preTitleFontSize": "",
      "titleFontSize": "",
      "subTitleFontSize": "",
      "descriptionFontSize": "",
      "titleColor": "",
      "preTitleColor": "",
      "subTitleColor": "",
      "contentTitleFontSize": "",
      "contentSubTitleFontSize": "",
      "contentDescriptionFontSize": "",
      "contentForegroundColor": "",
      "contentBackgroundColor": "",
      "tag": {
        "style": "",
        "label": "",
        "background": "",
        "foreground": ""
      },
      "layout": "slider",
      "classType": "group",
      "className": "",
      "image": null,
      "titleImage": null,
      "imagePosition": "top",
      "content": [
        {
          "title": "Manikandan",
          "subTitle": "Gururvayur, Kerala",
          "titleFontSize": null,
          "subTitleFontSize": "12px",
          "description": "<p>We were managing appointments manually earlier. After switching, booking, billing, and patient records became much more organized. The reminder system reduced missed appointments, and reporting gives us clear insights into daily performance. Highly recommended for small and medium clinics</p>",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2068.webp",
          "image_aspectRatio": "custom",
          "image_width": 100,
          "image_height": 150,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        },
        {
          "title": "Anjali",
          "subTitle": "Pullazhi, Thrissur",
          "titleFontSize": null,
          "subTitleFontSize": "12px",
          "description": "<p>Very helpful software. Easy to learn and works smoothly. Good support team as well.</p>",
          "descriptionFontSize": null,
          "useSectionFontSizes": false,
          "link": "",
          "foregroundColor": "",
          "backgroundColor": "",
          "fontSize": "",
          "textAlignment": "start",
          "imageAlignment": "left",
          "image": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/image%2069.webp",
          "image_aspectRatio": "custom",
          "image_width": 100,
          "image_height": 150,
          "image_mob": "",
          "image_mob_aspectRatio": null,
          "image_mob_width": 500,
          "image_mob_height": 500,
          "video": "",
          "date": null,
          "price": "",
          "mrp": "",
          "buttonHover": false,
          "buttonCaption": "",
          "tag": {
            "style": "",
            "label": "",
            "background": "",
            "foreground": ""
          }
        }
      ],
      "contentType": "static",
      "key": "",
      "showMore": false,
      "moreCaption": "Show More",
      "moreLink": "",
      "foregroundColor": "",
      "backgroundColor": "",
      "backgroundImage": "",
      "visible": true,
      "cols_xs_options": {
        "items": 1,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_md_options": {
        "items": 1,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      },
      "cols_xl_options": {
        "items": 2,
        "loop": false,
        "margin": 10,
        "autoplay": false,
        "autoplayTimeout": 3000,
        "dots": false,
        "center": false,
        "nav": false
      }
    }
  ],
  "footer": {
    "visible": true,
    "title": "",
    "displayName": "",
    "description": "",
    "copyright": "Copyright @ 2025 | Powered by Jaldee Soft Pvt Ltd",
    "logo": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/46805/site_assets/Frame%201.png",
    "logoAspectRatio": null,
    "variant": "minimal",
    "brandName": "",
    "addressLine1": "Vandana House, Palakkal Devi Temple Road",
    "addressLine2": "Ramanattukara, Kozhikode, Kerala 673633",
    "showDivider": true,
    "socialLinks": [
      {
        "platform": "instagram",
        "url": "https://instagram.com",
        "icon": "fa-instagram",
        "iconImage": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png",
        "visible": true
      }
    ],
    "columns": [
      {
        "title": "Quick Links",
        "links": [
          {
            "label": "Home",
            "link": "",
            "visible": true
          },
          {
            "label": "About Us",
            "link": "about",
            "visible": true
          },
          {
            "label": "Contact Us",
            "link": "contact",
            "visible": true
          },
          {
            "label": "Collections",
            "link": "collections",
            "visible": true
          }
        ]
      },
      {
        "title": "Policies",
        "links": [
          {
            "label": "Privacy Policy",
            "link": "privacy",
            "visible": true
          },
          {
            "label": "Refund Policy",
            "link": "refund",
            "visible": true
          },
          {
            "label": "Shipping Policy",
            "link": "shipping",
            "visible": true
          }
        ]
      },
      {
        "title": "Best Sellers",
        "links": [
          {
            "label": "Pre-Orders",
            "link": "preorders",
            "visible": true
          },
          {
            "label": "Premium Collections",
            "link": "premium",
            "visible": true
          },
          {
            "label": "New Arrivals",
            "link": "newarrivals",
            "visible": true
          },
          {
            "label": "Sale",
            "link": "sales",
            "visible": true
          }
        ]
      }
    ],
    "items": [
      {
        "title": "",
        "link": "/",
        "displayName": "Home",
        "icon": "",
        "visible": true
      },
      {
        "title": "phone",
        "link": "9605551784",
        "displayName": "Phone",
        "icon": "",
        "visible": true
      },
      {
        "title": "twitter",
        "link": "",
        "displayName": "Twitter",
        "icon": "",
        "visible": false
      },
      {
        "title": "shipping",
        "link": "",
        "displayName": "Shipping Policy",
        "icon": "",
        "visible": false
      },
      {
        "title": "about",
        "link": "",
        "displayName": "About Us",
        "icon": "",
        "visible": true
      },
      {
        "title": "contact",
        "link": "",
        "displayName": "Contact Us",
        "icon": "",
        "visible": true
      },
      {
        "title": "terms",
        "link": "",
        "displayName": "Terms & Conditions",
        "icon": "",
        "visible": true
      },
      {
        "title": "blogs",
        "link": "",
        "displayName": "Blogs",
        "icon": "",
        "visible": true
      }
    ],
    "foregroundColor": "#ffffff",
    "backgroundColor": "#000000"
  },
  "extras": {
    "store": "s-6101458-f",
    "selectedCatalogs": [
      "soc-6101458-4",
      "soc-6101458-3"
    ],
    "leadSDK": false
  }
} as PreviewTemplateConfig;
